# Github Actions
name: First
on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: cache-node-files-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit == '' || steps.cache.outputs.cache-hit == 'false'
        run: npm ci
      - name: Run Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: cache-node-files-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: (steps.cache.outputs.cache-hit == '') || steps.cache.outputs.cache-hit == 'false'
        run: npm ci
      - name: Run Tests
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: cache-node-files-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: (steps.cache.outputs.cache-hit == '') || steps.cache.outputs.cache-hit == 'false'
        run: npm ci
      - name: Run Build to Deploy
        run: npm run build
  deploy:
    needs: build
    uses: gorbadil/gh-actions/.github/workflows/reusable.yml
  report:
    needs: [deploy, lint]
    if: ${{failure()}}
    runs-on: ubuntu-latest
    steps:
      - name: Report Job
        run: |
          echo "#######################"
          echo "#{{ toJSON(github) }}"
          echo "#######################"
